### ISSUE TITLE
Accept or explicitly reject classes derived from BaseException for retrying and py27 compatibility?

### ISSUE THREAD

**Issue by nanflasted** [jd/tenacity#104]
First of all, thank you @jd and other contributors for maintaining tenacity, and making retrying easy.

Since the `tenacity` is the fork of `retrying`, a lot of code bases would want to upgrade/port from `retrying`, aside from a few common issues such as the ones pointed out in [this report](https://bugs.launchpad.net/python-oneviewclient/+bug/1635401), I ran into some compatibility issues:

https://github.com/jd/tenacity/blob/69cf4a74549b0820e6baaa188d0e72ced5ed58ad/tenacity/__init__.py#L297-L302

If I'm not mistaken, this part catches the exception thrown by the retrying function; `except Exception` is normally fine with catching all exceptions; however, when the retrying function uses a custom exception that inherits anything that's part of the `BaseException` (e.g., `SystemExit`, or just a class that inherits `BaseException`), `tenacity` will ignore any and all retrying settings and break: even if it is a bare `@retry` decorator without any arguments. This behaviour is introduced only in `tenacity`, because `retrying` library uses a bare `except:`, which catches *all* exceptions, and continues to retry.

Maybe consider adding a `except BaseException:` clause underneath the `except Exception` clause, and in that block, either accept or explicitly reject BaseException(s)? To the very least, documenting and warning about this issue seems worthy.

**Comment by blakev** [comment]
@nanflasted TIL there's a difference between `Exception` and `BaseException` +1

**Comment by penguinolog** [comment]
`Exception` is inherited from `BaseException`, but simple retry on `BaseException` will capture `KeyboardInterrupt`, `SystemExit` and `GeneratorExit`. Will be required to filter out as minimum part of them.
Also in all documents I seen, `BaseException` was not recommended to use as base class.

**Comment by jd** [comment]
It seems to me we could replace `Exception` here by `BaseException` and be good with it. At least that's the spirit of the code blocks. Anyone seens a potential issue doing this?
