### ISSUE TITLE
Discussion: Retry hook for logging or other

### ISSUE THREAD

**Issue by bodenr** [jd/tenacity#11]
One of the PRs I had on retrying [1] was to support a generic wait hook, suitable for logging or other per-retry operations.

I was looking at tenacity and wanted to confirm how I'd do this:

```py
def logged_wait(*args, **kwargs):
    # no-op wait just to log on each attempt
    print("Yet another logged attempt")
    return 0


@retry(wait=wait_combine(logged_wait, wait_fixed(1000)), ...)
def my_retried_func():
    # interesting retryable stuff here
```

Is this about right?

[1] https://github.com/rholder/retrying/pull/50

**Comment by jd** [comment]
@bodenr yeah, that should totally work. You can also use `after_attempts` and `before_attempts` if that suits you.
