### ISSUE TITLE
Cannot run in GAE standard

### ISSUE THREAD

**Issue by johnstill** [jd/tenacity#116]
Google App Engine's "standard" environment blacklists the `ctypes` module, which `monotonic` uses fairly heavily.  As a result, we cannot use `tenacity` on gae standard either b/c the import fails.  Is `monotonic` a hard requirement of this lib, or would it be possible to degrade from `monotonic` to a function from `time` or another stdlib module on ImportError rather than fail?

**Comment by jd** [comment]
Are you using Python 3 or Python 2.7 @johnstill ?
This is going to be fixable for Python 3, but kinda hard for Python 2.

**Comment by jd** [comment]
Yeah it's a trade-off, not using monotonic time can be problematic and have side-effect. I've fixed it for Python 3, but for Python 2, I don't think I'll do anything. It's dead and a bad idea at this point anyway. :(
