### ISSUE TITLE
Feature suggestion: `after_sleep` keyword argument

### ISSUE THREAD

**Issue by JoshPaterson** [jd/tenacity#136]
I'm sorry if I'm overlooking an obvious way of doing this, but I'm looking for a way to specify a function to be run before the decorated function is retried, but only on the retries, not the first attempt.

My suggestion is to have a keyword argument `after_sleep` that is similar to the already existing keyword arguments `before`, `after`, and `before_sleep`.

Thanks for your work on this package, it is very useful!

**Comment by jd** [comment]
You can use `before` and check the value of `trial_number` that is being passed.
