### ISSUE TITLE
Access object that contains the retrying function

### ISSUE THREAD

**Issue by girstenbrei** [jd/tenacity#150]
So, I actually don't know if this is possible or if I just don't know enough about decorators. Here's what I would like to do:

```python
import some_db_module
from tenacity import wait_fixed, retry

class DBConnection:
  def __init__(self, settings):
    self.settings = settings
    self.connection = some_db_module.connect(settings)

  def reopen_connection(self):
    self.connection = some_db_module.connect(self.settings)

  @retry(wait=wait_fixed(3), after=self.reopen_connection)
  def send(self):
    self.connection.execute_query('SELECT * FROM this_may_fail')


c = DBConnection('db-settings')
c.send()
```

This does not work, as the send function decorator cannot access self. If I change it to `@retry(wait=wait_fixed(3), after=reopen_connection)`, the reopen_connection function is called but with self being the function itself, not the object.

Is there a way to set a function in the retry argument and access the objects variables the function belongs to when it is called? This would enable me to use all the awesome retry features of tenacity, they would be perfect: try to reconnect, but do exponential backoff and stop after a certain time etcetera ...

Thank you for your amazing work!
Chris

**Comment by berislavlopac** [comment]
Tenacity is not very well suited for retrying instance methods. In fact, it can be downright dangerous if you have multiple instances retrying the same method at the same time, e.g. in multiple threads or on the async loop. I suggest you to try rewriting this as regular functions instead.

**Comment by jd** [comment]
I think you can use something like:

```python
def send(self):
    r = tenacity.Retrying(wait=wait_fixed(3), after=self.reopen_connection)
    r.call(self.connection.execute_query, 'SELECT * FROM this_may_fail'))
```
