### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by GratefulDave** [jd/tenacity#157]
I am new to Python and may be making a beginner's mistake. I am using Python 3.7.1 in an Anaconda virtual environment and installed tenacity with PIP am using the following code:

```
from tenacity import retry

@retry(stop=stop_after_attempt(7))
def stop_after_7_attempts():
    print("Stopping after 7 attempts")
    raise Exception
```
and receiving the following error:
`NameError: name 'stop_after_attempt' is not defined`. 

What am I doing wrong?

**Comment by GratefulDave** [comment]
I have installed this successfully in my environment, but it still does not work.

**Comment by jd** [comment]
You miss `from tenacity import *`.

**Comment by GratefulDave** [comment]
I am using Python 3.7.1 and successfully installed tenacity with pip.
```
import logging
from tenacity import *

class MyException(Exception):
    pass

@retry(stop=stop_after_attempt(7))
def stop_after_7_attempts():
    print("Stopping after 7 attempts")
    raise Exception

`NameError: name 'retry' is not defined`
```

**Comment by fat0** [comment]
The docs are not clear on what to import, it took me a while to figure it out. They say the following:
```
from tenacity import retry
```
They need to say the following instead:
```
from tenacity import *
```

**Comment by GratefulDave** [comment]
It still persists.
