### ISSUE TITLE
I am using Python 3.7.1 and successfully installed tenacity with pip.

### ISSUE THREAD

**Issue by GratefulDave** [jd/tenacity#158]
I am using Python 3.7.1 and successfully installed tenacity with pip.
```
import logging
from tenacity import *

class MyException(Exception):
    pass

@retry(stop=stop_after_attempt(7))
def stop_after_7_attempts():
    print("Stopping after 7 attempts")
    raise Exception

`NameError: name 'retry' is not defined`
```

_Originally posted by @GratefulDave in https://github.com/jd/tenacity/issue_comments#issuecomment-451710319_

**Comment by jd** [comment]
Which version of tenacity do you have installed?

**Comment by GratefulDave** [comment]
5.0.2

**Comment by jd** [comment]
That does not make sense.

```python
>>> from tenacity import *
>>> retry
<function retry at 0x10ae59730>
```

Are you sure you're pasting the right snippet and right error?

**Comment by jd** [comment]
The code you pasted above works perfectly. That's why I suspect you're not actually executing what you think you're executing, or something like that.

**Comment by GratefulDave** [comment]
I think it may be an issue with how I have been install libraries with pip/conda. I'll close this for now and see if I can't figure it out.
