### ISSUE TITLE
retry doesn't pass retry_state to method

### ISSUE THREAD

**Issue by rafalkrupinski** [jd/tenacity#163]
When using a bound method as a 'before' function (possibly others) that takes retry_state causes an error:

```    @_utils.wraps(fn)
    def wrapped_before_func(retry_state):
        # func, trial_number, trial_time_taken
        warn_about_non_retry_state_deprecation('before', fn, stacklevel=4)
        return fn(
            retry_state.fn,
>           retry_state.attempt_number,
        )
E       TypeError: _retry_refresh_token() takes 2 positional arguments but 3 were given
```

2 positional arguments above are self, retry_state

calling ```inspect.isfunction()``` on a bound method returns false, but then the code assumes it's a callable object. In result the compatibility wrapper is used which tries to call the method with parameters for the old-style before function.

https://github.com/jd/tenacity/blob/5f3d822c22ef435a57081a314bcb61b1c9f7b326/tenacity/compat.py#L29

**Comment by jd** [comment]
@rafalkrupinski Can you check if #164 fixes your issue?

**Comment by rafalkrupinski** [comment]
Works for me, thanks
