### ISSUE TITLE
Get away from using milliseconds everywhere

### ISSUE THREAD

**Issue by harlowja** [jd/tenacity#17]
The usage of milliseconds never quite seemed to make sense (all time routines in python take floating point numbers) to myself, so I"m not really such a big fan of keeping with that. Thoughts about moving away from that model and just using the normal floating point numbers to do time tracking and such (not forcing everything into milliseconds?); perhaps if really needed we can make it configurable (although I'd rather not).

**Comment by jd** [comment]
I'd be good going with floating points seconds. That's what I use with most of stuff like Gnocchi, jsut because second is a SI unit and because you can go down to nanoseconds – or not, but you can 🍭

**Comment by harlowja** [comment]
Ya, I never quite understand why the original author went with the milliseconds stuff, perhaps cause java was what he used before (and that only shows milliseconds)?

**Comment by harlowja** [comment]
Doesn't this also require the following places to change:

https://github.com/jd/tenacity/blob/master/tenacity/__init__.py#L160-L163

https://github.com/jd/tenacity/blob/master/tenacity/__init__.py#L128-L129

I was also thinking to drop that as well.
