### ISSUE TITLE
Decorators should be higher order functions

### ISSUE THREAD

**Issue by CMCDragonkai** [jd/tenacity#171]
I expected decorators to be higher order functions, so I'm curious why this is not working:

```py
import tenacity

class MyError(Exception):
  pass

def f():
  raise MyError()

f_ = tenacity.retry(f, stop=tenacity.stop_after_attempt(3))

f_()
```

The `stop` condition is not being understood. I understand that there's `tenacity.Retrying` but still most decorators I use can be used in this way. So I think this is strange that this doesn't work. Also this is needed when you need to use decorators in a dynamic way. Such as when the retry conditions are not static parameters, but dynamically injected from other code.

Related: https://github.com/jd/tenacity/issues/155

**Comment by jd** [comment]
You mean:

`f_ = tenacity.retry(stop=tenacity.stop_after_attempt(3))(f)`

**Comment by CMCDragonkai** [comment]
Decorators can definitely operate like the way I just demonstrated:

```py
import functools

def prepost(func=None, *, prefix=''):
    def prepost_(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            print(f'{prefix} start')
            result = func(*args, **kwargs)
            print(f'{prefix} end')
            return result
        return wrapper
    if func is None:
        return prepost_
    else:
        return prepost_(func)

@prepost(prefix='outer')
@prepost(prefix='inner')
@prepost
def multiplication(x, y):
    print('middle')
    return x * y

def addition(x, y):
    return x + y

addition_ = prepost(prepost(prepost(addition), prefix='inner'), prefix='outer')
```

Execute `addition_(1,2)`.

**Comment by jd** [comment]
They can if they are written that way.
