### ISSUE TITLE
<class 'RuntimeError'>: generator raised StopIteration

### ISSUE THREAD

**Issue by GratefulDave** [jd/tenacity#172]
I am getting `<class 'RuntimeError'>: generator raised StopIteration` when I use the following decorator `@retry(stop=stop_after_attempt(5), wait=wait_random_exponential(multiplier=0.15, max=60))` on a function.  When, I remove the decorator the error goes away. 

I am importing the libraries like this:
`from tenacity import retry, stop_after_attempt, wait_random_exponential`.

Any suggestions would be greatly appreciated.

**Comment by jd** [comment]
If you don't provide a minimal code example that allows us to reproduce it, it'll be impossible to help.

**Comment by GratefulDave** [comment]
Sorry about that. Here ya go:
```import boto3
from boto3.dynamodb.conditions import Attr, Key
import json
from tenacity import retry, stop_after_attempt, wait_random_exponential

dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('EmailTemplate')

def put(email_template):

    response = table.put_item(
        Item={
            'Id': email_template['name'],
            'Subject': email_template['subject'],
            'Html': email_template['html'],
            'Text': email_template['text']
            })
    return

@retry(stop=stop_after_attempt(5), wait=wait_random_exponential(multiplier=0.15, max=60))
def get(template_name):

    print(f'[+] START: email_template.get {template_name}')
    response = table.query(KeyConditionExpression=(Key('Id').eq(template_name)))['Items'][0]
    print('[+] OK')
    return response
```

**Comment by jd** [comment]
I can't run that piece of code obviously, so it's impossible to reproduce it…

My guess is that your `table.query` function is an iterator which might return 0 element and raises `StopIteration` right away. But it's really a wild guess.

Anyhow, this is an issue around your code, not tenacity.
