### ISSUE TITLE
Different wait strategy for different exceptions

### ISSUE THREAD

**Issue by panthony** [jd/tenacity#174]
Hi !

Is there a way to have a different wait strategy depending on the raised exception ?

Some exceptions would require a backoff whereas others would require to keep the pressure.

Or for this particular case I should use nested method with different `@Retry` annotation ?

Thanks for this awesome library.

**Comment by jd** [comment]
I _think_ you could do that by using two `@retry` decorator one of top of each other. I never tried it but it might be doable. However, if your function raises exception A and then B and then A, the behaviour might be weird.

The best method might be to write your own `wait` function that would introspect why the retry failed.

**Comment by panthony** [comment]
Since i'm using `fct.retry.XXX` in my tests to bypass wait time it might not be a good idea to have multiple annotations.

I'll try what you suggest and use a custom wait function, ideally reusing one of the original wait method under the hood.

Just wanted to be sure I did not miss anything on how we can compose the wait/retry logic.

Thanks for the quick response.
