### ISSUE TITLE
wait_exponential has unexpected first delay

### ISSUE THREAD

**Issue by cyounkins** [jd/tenacity#175]
Hi there! Thank you for `tenacity`!

The first delay for `wait_exponential` is `2 * multiplier`, and to me that is unexpected. In version `5.0.4`:

```
In [14]: t0 = time.time()
    ...: t_last = t0
    ...: @retry(wait=wait_exponential(multiplier=0.2), stop=stop_after_attempt(5))
    ...: def wait():
    ...:     current_time = time.time()
    ...:     global t_last
    ...:     print("%.2f - %.2f" % (current_time - t0, current_time - t_last))
    ...:     t_last = current_time
    ...:     raise Exception
    ...: print("total - delta")
    ...: wait()
total - delta
0.00 - 0.00
0.40 - 0.40
1.21 - 0.80
2.81 - 1.60
6.01 - 3.20
```

To me it would make more sense for the first delay to be `1 * multiplier`. Others may expect the first retry to occur immediately with no delay, or maybe they want the sequence to be 0.1, 0.2, 0.4, 0.8, etc. which doesn't seem possible with just `wait_exponential`.

Can this be considered a bug? Is this unexpected to others, or do others want to be able to create the sequence above?

**Comment by jd** [comment]
The first delay is like the rest of the, it's `(base_exp ** retry_attempt_number) * multiplier`, which is `2 * multiplier` if your base is `2` indeed.

So the default is: `2, 4, 8, 16`… which sounds good to me. Then it's up to you to change the `base` or the multiplier to tweak it`.

Unless I miss something?

**Comment by cyounkins** [comment]
Yeah that makes sense. I think the reason I got confused is that when I think of the sequence `2, 4, 8, 16...` I think of the _multiplier_ as `2` where here it is the `base`.

So you can "back up" the sequence by dividing the `multiplier` by the `base_exp` or a power of `base_exp`. So to get 0.1, 0.2, 0.4, 0.8...

```
In [16]: t0 = time.time()
    ...: t_last = t0
    ...: @retry(wait=wait_exponential(multiplier=0.05), stop=stop_after_attempt(5))
    ...: def wait():
    ...:     current_time = time.time()
    ...:     global t_last
    ...:     print("%.2f - %.2f" % (current_time - t0, current_time - t_last))
    ...:     t_last = current_time
    ...:     raise Exception
    ...: print("total - delta")
    ...: wait()
    ...:
total - delta
0.00 - 0.00
0.10 - 0.10
0.31 - 0.20
0.71 - 0.40
1.51 - 0.80
```

Still, at first glance of `wait_exponential(multiplier=0.05)` I would expect the first delay to be `0.05` and not `0.1` and would advocate for the exponent to be offset by `-1`.

**Comment by jd** [comment]
If you offset the exponent by `-1` then your first wait time is always `0`, no?

**Comment by cyounkins** [comment]
I don't think so. With the default arguments, the sequence is `2, 4, 8, 16...` which means for the first delay `(2 ** retry_attempt_number) * 1 == 2` and so `retry_attempt_number = 1` for the first delay calculation.

If `retry_attempt_number = 1`, then `(base_exp ** (retry_attempt_number - 1)) == 2 ** 0 == 1`

**Comment by jd** [comment]
Ah, maths are hard 🤦‍♂ 

Yeah I think it'd make sense to change the formula to use `retry_attempt_number - 1`. Go for a PR?
