### ISSUE TITLE
Asyncio: iscoroutinefunction does not work with tenacity

### ISSUE THREAD

**Issue by sbrandtb** [jd/tenacity#181]
When decorating an `async` function with `@retry`, `asyncio.iscoroutinefunction(f)` unexpectedly returns `False`, because the wrapping function, in fact, is no coroutine.

This is a problem in some libraries that are using this way of determining if they are handling an async function or not (in my case: trafaret).

**Comment by bersace** [comment]
Hi @sbrandtb I'm investigating.

**Comment by sbrandtb** [comment]
Thanks!
