### ISSUE TITLE
Question: how to get actual Exception?

### ISSUE THREAD

**Issue by Gatsby-Lee** [jd/tenacity#185]
Hello,
Can you help me find a way to get actual exception instance when fully retried?
I tried multiple ways, but haven't figured it out.

For example, this code raises exception.
```
print(1/0)
```

```
Traceback (most recent call last):
  File "test1.py", line 6, in <module>
    print(1/0)
ZeroDivisionError: division by zero
```

If I wrap divisionByZero function below, how can I get the actual Exception instance?
```python
from tenacity import (
    retry,
    stop_after_attempt
) 

@retry(stop=stop_after_attempt(1))
def divisionByZero():
   print(1/0)

try:
    divisionByZero()
except Exception as e: 
    print(e)
    # how can I get `ZeroDivisionError` instance here?
```

P.S. I tried to label it with `Question`, but couldn't find the way.

Thank you

**Comment by jd** [comment]
Two options:

1. You  catch the `RetryError` and call `RetryError.reraise()` to get the original exception
2. You add `reraise=True` in your `@retry` decorator to have directly the `ZeroDivisionError`.

**Comment by Gatsby-Lee** [comment]
@jd Thank you very much :) It worked as I expected. I'm using `tenacity` in pypi pkg called [retry-redis](https://github.com/Gatsby-Lee/retry-redis)

Again, Thank you for building good pkg to use :)

**Comment by Gatsby-Lee** [comment]
@jd you can close this issue. ;)
