### ISSUE TITLE
Not working with type checker Pyright, https://github.com/Microsoft/pyright

### ISSUE THREAD

**Issue by Afsarsoft** [jd/tenacity#187]
First of all, thanks so much for this. It is great. Unfortunately, it is not working with type checker Pyright
https://github.com/Microsoft/pyright

**Any possibility to add Static Type Hinting?**
For example, I get error for stop_after_attempt in Pyright for following code:
```python
@retry(stop=stop_after_attempt(3))
def some_stuff() -> str:
    user_unit: str = ''

    user_unit = str.upper(input('Enter L for pounds or K for Kilos: '))
    if user_unit != 'L' and user_unit != 'K':
        print(f'Invalid value! You entered {user_unit}')
        raise Exception(f'Invalid Value! Error in {__name__}')
    else:
        print(f'Thanks. You entered {user_unit}')
        return user_unit
```

when I use the 
``` # pyright: strict ```

I even get error for @retry in the following code 
```python
@retry
def some_stuff() -> str:
    user_unit: str = ''

    user_unit = str.upper(input('Enter L for pounds or K for Kilos: '))
    if user_unit != 'L' and user_unit != 'K':
        print(f'Invalid value! You entered {user_unit}')
        raise Exception(f'Invalid Value! Error in {__name__}')
    else:
        print(f'Thanks. You entered {user_unit}')
        return user_unit


print(some_stuff())

```

**Comment by jd** [comment]
I'm not sure that's something we can do while keeping compatibility with Python 2.

**Comment by spackard** [comment]
It is possible, the typing has to be done with comments. We've run into the same issue with mypy, another type checker: https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code

**Comment by ian-h-chamberlain** [comment]
This issue is stale since #221 was merged, correct?

**Comment by sileht** [comment]
Yeah we can close this one.
