### ISSUE TITLE
How to use two retry?

### ISSUE THREAD

**Issue by Gatsby-Lee** [jd/tenacity#188]
Hi I have question.

What if I'd like to wrap a function with different retry with different wait time?

For example,
Let's assume there is a function which raises `ConnectionException`, `TimeoutException`.
I'd like to retry with exponential_wait for `TimeoutExceptoin`, but I'd like retry without any sleep for `ConnectionException`

Can you tell me how I can handle this case?

Thank you

**Comment by jd** [comment]
You can write your own `wait` function and inspect the `RetryCallState` thas is passed as argument. Based on the type of exception, you can call the wait function that you prefer.

**Comment by Gatsby-Lee** [comment]
@jd Thank you. Do you mean that I can use [this](https://github.com/jd/tenacity#other-custom-callbacks)?

**Comment by Gatsby-Lee** [comment]
@jd hello,
I'm trying to implement a function that can take retry_state.
How can I the exception instance from retry_state?

Even after leaving this comment, I will keep trying to find out what I need.
However, if you can guide me, I can build it quickly.

Thank you

**Comment by Gatsby-Lee** [comment]
oh.. I made this work first

`
isinstance(retry_state.outcome.exception(), redis.exceptions.ConnectionError)
`

**Comment by Gatsby-Lee** [comment]
@jd 
I tried this way.

`

from tenacity import _utils
from tenacity import compat as _compat
from tenacity.wait import wait_base


class wait_exponential_onlyif_exception_type(wait_base):

    def __init__(self, wait_onlyif_exception=Exception,
                 multiplier=1, max=_utils.MAX_WAIT, exp_base=2, min=0):
        self.exception_types = wait_onlyif_exception
        self.multiplier = multiplier
        self.min = min
        self.max = max
        self.exp_base = exp_base

    @_compat.wait_dunder_call_accept_old_params
    def __call__(self, retry_state):

        e = retry_state.outcome.exception()
        if not isinstance(e, self.exception_types):
            return 0

        try:
            exp = self.exp_base ** (retry_state.attempt_number - 1)
            result = self.multiplier * exp
        except OverflowError:
            return self.max
        return max(max(0, self.min), min(result, self.max))
`

Thank you for your help.

**Comment by jd** [comment]
Yes that looks good. :)

**Comment by Gatsby-Lee** [comment]
@jd Thank you for your comment
