### ISSUE TITLE
Missing kwargs in retry helper in __init__.py

### ISSUE THREAD

**Issue by thehesiod** [jd/tenacity#197]
on this section:
```python
    if len(dargs) == 1 and callable(dargs[0]):
        return retry()(dargs[0])
```
it should be:
```python
    if len(dargs) == 1 and callable(dargs[0]):
        return retry(**dkw)(dargs[0])
```

**Comment by jd** [comment]
Would you mind sending a pull request with a unit test?

**Comment by jd** [comment]
Not a bug 🤷‍♂

**Comment by thehesiod** [comment]
this is a bug, you're dropping the `dkw` here: https://github.com/jd/tenacity/blob/master/tenacity/__init__.py#L96

**Comment by jd** [comment]
Did you read the discussion on #199 @thehesiod?

**Comment by thehesiod** [comment]
what about it?  it's a bad test, you're obviously dropping the kwargs on the floor so this is most definitely a bug.
