### ISSUE TITLE
API reference documentation is broken

### ISSUE THREAD

**Issue by alexwlchan** [jd/tenacity#207]
I'm writing a blog post about tenacity, and I'd like to include some reference links that explain how to use it (for example, the different functions you can pass to `wait`).

There is API reference documentation, but there's nothing there: https://tenacity.readthedocs.io/en/latest/api.html

Hard to show people the module if there aren't any API docs!

**Comment by alexwlchan** [comment]
Aha, I see the issue. PR incoming.

**Comment by GPHemsley** [comment]
How do we kick off a new build of the docs?

**Comment by alexwlchan** [comment]
I think you need to be an admin on ReadTheDocs and trigger it manually, or set up CI in RTD to build on new pushes to the main branch.

**Comment by jd** [comment]
It's always rebuild when something is pushed to `master.`

**Comment by alexwlchan** [comment]
@jd That looks like a different project?

I don't think tenacity has had a docs build since May: https://readthedocs.org/projects/tenacity/builds/

**Comment by jd** [comment]
🤦‍♂ 

Don't do several things at the same time.

That's weird, I was sure it was auto building? Anyway I just trigged a new build manually:

https://readthedocs.org/projects/tenacity/builds/10122966/

It seems to work fine.

I just realized I never enabled the GitHub/RTD integration and I just did so the next push should trigger a build!

**Comment by alexwlchan** [comment]
Looks great now, thanks! :D
