### ISSUE TITLE
Allow configurable defaults

### ISSUE THREAD

**Issue by afischer-opentext-com** [jd/tenacity#210]
Hi, 

is there a way to re-configure the default configuration? I crawled the code base but failed to find something. 

In the code base I am maintaining the retry annotation is heavily used (more than 200 times). The vast majority of the calls looks equal, e.q.

```python
import logging

from tenacity import (before_sleep_log, retry, stop_after_attempt,
                      wait_exponential)

log = logging.getLogger(__name__)

@retry(before_sleep=before_sleep_log(log, logging.INFO), reraise=True, stop=stop_after_attempt(15), wait=wait_exponential(multiplier=1, min=1, max=10))
def something():
    pass
```

It would be great to have the ability to configure some kind of configuration group, something like the following as it help to reduce duplicate code.

```python
tenacity.config_group('foo', reraise=True, stop=stop_after_attempt(15), wait=wait_exponential(multiplier=1, min=1, max=10))

# and later

@retry(config_group='foo', before_sleep=before_sleep_log(log, logging.INFO))
def something():
    pass
```

**Comment by markhu** [comment]
Could you kludge this with something like `@retry(eval(config_group['foo']))` ?

**Comment by jd** [comment]
What's the problem with using something like:

```python
r = tenacity.Retrying(<your conf>)

r.wraps
def myfunc1():
    pass

r.wraps
def myfunc2():
    pass
```

?

**Comment by afischer-opentext-com** [comment]
No problem! I opened the ticket asking for exactly something like this...
I was not aware about the functionality, it is not explicitly documented.
This also has the advantage that viewer objects are created.
