### ISSUE TITLE
import star is an antipattern

### ISSUE THREAD

**Issue by PeterSulcs** [jd/tenacity#214]
but is shown in line 86 of doc/source/index.rst

`    from tenacity import *`

https://www.python.org/dev/peps/pep-0008/#imports

> Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools. There is one defensible use case for a wildcard import, which is to republish an internal interface as part of a public API (for example, overwriting a pure Python implementation of an interface with the definitions from an optional accelerator module and exactly which definitions will be overwritten isn't known in advance).

**Comment by moshez** [comment]
This issue seems to be resolved. Would you mind closing it?

**Comment by PeterSulcs** [comment]
Comments were added to the code snippet. Closing this issue.
