### ISSUE TITLE
Retrying compatibility: seconds vs. ms

### ISSUE THREAD

**Issue by bodenr** [jd/tenacity#22]
By default seconds are used for most stop/retry predicates in tenacity right now. However in retrying ms was the default.

While I don't disagree with seconds being the base of choice here, it causes more work for anyone migrating from retrying -> tenacity.

For example migrating retrying code like [1] to tenacity requires the measurements parameters passed to be changed to account for the fact that tenacity uses seconds.

I assume this is intended correct, and folks migrating just have to deal with it?

[1] https://github.com/openstack/neutron/blob/master/neutron/agent/common/ovs_lib.py#L80

**Comment by jd** [comment]
Yes, see https://github.com/jd/tenacity/issues/17
