### ISSUE TITLE
'Retrying' object is not iterable

### ISSUE THREAD

**Issue by mulawamichal** [jd/tenacity#220]
executing the code from documentation:
```
from tenacity import Retrying, RetryError, stop_after_attempt

try:
    for attempt in Retrying(stop=stop_after_attempt(3)):
        with attempt:
            raise Exception('My code is failing!')
except RetryError:
    pass
```
results in:
`E   TypeError: 'Retrying' object is not iterable`

Checked on python3.6 and python3.7

**Comment by mulawamichal** [comment]
ok, i ws using version 5.1.4, as it appeared to be lates on in https://github.com/jd/tenacity/releases . but there are also some newer tags (not promoted to release?) - and on version 6.1.0 it works ok...

**Comment by jd** [comment]
I'm too lazy to do releases on GitHub, I simply create a git tag.
