### ISSUE TITLE
AsyncRetrying does not work in the latest release on PyPI

### ISSUE THREAD

**Issue by espdev** [jd/tenacity#229]
tenacity v6.1.0 from PyPI, Python 3.7

I try to use `AsyncRetrying` in my async code, but I get an error: `TypeError: 'async for' requires an object with __aiter__ method, got AsyncRetrying`.

The example [from doc](https://tenacity.readthedocs.io/en/latest/#retrying-code-block):

```python
import asyncio
from tenacity import AsyncRetrying, RetryError, stop_after_attempt

async def main():
    try:
        async for attempt in AsyncRetrying(stop=stop_after_attempt(3)):
            with attempt:
                raise Exception('My code is failing!')
    except RetryError:
        print('foo')

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

I looked at the source code and I do not understand how it should work without `__aiter__` method.

Also, I see the following code in master:
https://github.com/jd/tenacity/blob/c5a8abb404c50bddd9881c69b995c343ab7b4991/tenacity/_asyncio.py#L57-L73

It seems, it should work right. When do you plan to new release?

**Comment by jd** [comment]
Just pushed 6.2.0.

**Comment by espdev** [comment]
@jd Thanks!
