### ISSUE TITLE
[Feature Request] Wait till internet connection is up?

### ISSUE THREAD

**Issue by RafayGhafoor** [jd/tenacity#238]

**Comment by jd** [comment]
That's a bit… unclear and wild. :)

**Comment by RafayGhafoor** [comment]
So, the internet might be not working or gets disconnected during the running of a program and there is a use case, while internet is not back alive on device, sleep and retry after x seconds. Can tenacity do that?

**Comment by labstersteve** [comment]
Do you mean that if the specific cause of delay is loss of Internet connectivity you would like a separate retry policy? This request is not currently sufficiently detailed to consider whether implementation would be realistic.

**Comment by RafayGhafoor** [comment]
@labstersteve, Yes.

**Comment by AIGeneratedUsername** [comment]
@RafayGhafoor Why you can not (or do not want) to catch and handle some kind of `ConnectionError` which must be raised if the code can not connect to some resource?
