### ISSUE TITLE
Retry if not exception type?

### ISSUE THREAD

**Issue by william-silversmith** [jd/tenacity#256]
Hi, I was wondering if there's an easy way to say retry for everything except this list of exceptions?

For example, I want to retry for all server errors but not client errors.

**Comment by yuvadm** [comment]
You probably want to use `retry_unless_exception_type`  and chain it with boolean or operators for all the different types you want to ignore for the retry behavior.

**Comment by asqui** [comment]
Even simpler: `retry_unless_exception_type` can also take a tuple of exception types.

**Comment by yuvadm** [comment]
I ran into a serious pitfall with `retry_unless_exception_type` - see https://github.com/jd/tenacity/issues/137#issuecomment-711132814

**Comment by asqui** [comment]
@william-silversmith : When you say "retry for everything except this list of exceptions" does _everything_ include successful returns, or just exceptions, from the function being wrapped?

Intuitively, I suspect that you never want to retry on successful results. Unfortunately `retry_unless_exception_type` will retry on successful results (as detailed in #137) which is not what you want.

I have just proposed a new method, `retry_if_exception_not_of_type` which will do what I suspect you want. Feel free to comment on #137 with your feedback on this proposal.

**Comment by william-silversmith** [comment]
Yes, I want to retry only on server errors. If the action succeeds it should not retry. If the error is the client's fault (e.g. wrong authentication or even something lower level) it should not retry until the problem is inspected manually.
