### ISSUE TITLE
Passing custom arguments to callback

### ISSUE THREAD

**Issue by nitishxp** [jd/tenacity#262]
Hi want to pass custom arguments to callback function

def retry_end_callback(retry_state, arg1, arg2..):
     # can also access arg1 arg2 passed in the call back function

tenacity.retry(retry_error_callback=retry_end_callback(arg1, arg2.)    ) 

Can i know how to do it

**Comment by asqui** [comment]
This can be generalised to a question of:

> Given a function that takes three arguments `f(a,b,c)` how do I provide values for `b` and `c`, and turn it into a function that only takes only one argument, `g(a)`.

You can achieve this by making use of closures, or, more easily, with [`functools.partial()`](https://docs.python.org/2/library/functools.html#functools.partial):

```
import functools
g = functools.partial(retry_end_callback, arg1=..., arg2=...)
tenacity.retry(retry_error_callback=g)
```
