### ISSUE TITLE
Tenacity always sleeps before executing anything???

### ISSUE THREAD

**Issue by t4n1o** [jd/tenacity#271]
The tenacity seems to sleep before running the function, even before retrying. This cannot be the intended implementation. Try this code. Notice there is a 1 second wait time between every print.
```
from tenacity import *

class Cat:
    a=0
    @retry(wait=wait_fixed(1), retry=retry_unless_exception_type(RuntimeError))
    def call(self, param):

        self.a += 1
        print(f'a {self.a}')
        if (self.a % 4) == 0:
            print ('Will try again')
            raise TryAgain
        elif (self.a % 20) == 0:
            print ('Will try again')
            raise Exception
        elif (self.a % 30) == 0:
            raise RuntimeError #Actually goes through


if __name__ == "__main__":
    print('Starting')
    cat=Cat()
    while True:
        cat.call(4)
```

**Comment by jd** [comment]
Each iteration raises `TryAgain` which makes it retry following your demand of sleeping for 1 second.

**Comment by jd** [comment]
Your `while True` is never executed: `cat.call(4)` retries forever because you never raise `RuntimeError` which is the condition you defined to stop retrying.
I think you meant `retry_if_exception_type(RuntimeError)`.

**Comment by t4n1o** [comment]
I see. So Tryagain always forces a retry (as I read the code+documentation). This I understand.

I believe Exception, specifically in my example, does not create a retry.

The RuntimeError does go off and halts the program as intended.

My actual issue is: **why is there a sleep/wait time of 1 second between printing 1, 2, 3**. Tryagain is supposed to happen if the number is divisble by 4.

1, 2, 3 is supposed to be printed instantly, not 1 sec apart. Or am I missing your intention?

**Comment by t4n1o** [comment]
Ok got it, the correct code is:
    @retry(wait=wait_fixed(1), retry=(retry_unless_exception_type(RuntimeError) & retry_if_exception_type(TryAgain)))

**Comment by jd** [comment]
I think you don't understand. Your original code *always retries until you raise `RuntimeError`*. Your code *never* raises `RuntimeError` so the code is retried forever, sleeping one second between each retry.

**Comment by t4n1o** [comment]
That simply isn't true: when I run it, it raises a Runtime error when a=30 ie is divisble by 30 with no remainder.

The thing that I was trying to change is the wait time of (1) between each increase of a. I wanted a parameter in the decorator to control whether we wait _wait_with exponential backoff, _retry immediately_ or _stop retrying_.

I was connecting to an API with a rate limit, where you can make 50 requests, and then have to stop at the wait time. That's why I was trying to figure out if I can raise specific exceptions to have this 3-fold functionality. But it's okay my use case was too complicated I'll just rewrite my own handler/decorator.
