### ISSUE TITLE
This is definitely not an issue, and the more I think about it, the less I see a clean solution to this problem. The thing is that if you have a retry rules which states "retry if the result is None for 10 times", then your function _will_ raise `RetryError`, no matter what.

### ISSUE THREAD

**Issue by xiatian52673** [jd/tenacity#272]
This is definitely not an issue, and the more I think about it, the less I see a clean solution to this problem. The thing is that if you have a retry rules which states "retry if the result is None for 10 times", then your function _will_ raise `RetryError`, no matter what.

So it means depending on the retrying condition, the error raised might be different. I don't think it's a good design per say, and I think fixing the function using retrying to handle that condition correctly is the good choice (like you did).

However, we could help by having a `reraise()` method so you could wrote:

``` python
try:
    my_retried_fn()
except tenacity.RetryError as retry_err:
    retry_err.reraise()
```

Though if the `RetryError` has no exception (because e.g. it retried 10 times because the result was None) we would _anyway_ raise the `RetryError`.

_Originally posted by @jd in https://github.com/jd/tenacity/issues/24#issuecomment-246938923_

**Comment by jd** [comment]
What is that?
