### ISSUE TITLE
Custom callbacks behavior is dependent of argument name

### ISSUE THREAD

**Issue by Yomguithereal** [jd/tenacity#280]
Hello @jd, thanks for your tremendous work on this very useful library. I just stumbled upon something today while adding a `before_sleep` callback. As I understand it, if the argument given to the function is not named `retry_state` then its behavior will not be the same as it will be passed the `Retrying` object itself and some kwargs. I understand this has something to do with retro-compatibility since the function will be fired from a wrapper living in the `compat.py` file. I think I know why you wouldn't change this not to break anyone's old code but would you accept a PR adding some bits to the documentation explaining that you should keep to this argument name so that people don't struggle with the same issue as I did?

**Comment by jd** [comment]
Hey!

I just removed the compat code on master so make sure it still applies.

Otherwise, I'm all for it! 👍

**Comment by Yomguithereal** [comment]
Hello @jd I am working with pypi version `6.3.1` which still has compat code. I will wait for next release and see if it still applies (I think it will not). So feel free to close if convenient :)

**Comment by Yomguithereal** [comment]
I can confirm that the issue has been fixed with v7.0.0 from pypi. Thanks @jd.
