### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by and-semakin** [jd/tenacity#291]
Python 2 has [reached its EOL](https://www.python.org/dev/peps/pep-0373/) about 1.5 years ago. Even AWS Lambda is going to [deprecate their Python 2 runtime](https://aws.amazon.com/blogs/compute/announcing-end-of-support-for-python-2-7-in-aws-lambda/) soon. Supporting this old version of Python prevents using modern language features, for example, PEP-484 inline type hints (not those comments).

You can go the same way as [guys from Pallets Project did](https://palletsprojects.com/blog/ending-python2-support/) and use the `python_requires` package metadata. It will allow you to release the next version without Python 2 support (let's say 6.0.0), but Python 2 users will still be able to download and use the latest available version with Python 2 support (let's say 5.1.5).

Is there any plan of dropping Python 2? What do you think?

**Comment by and-semakin** [comment]
As we can see [here](https://pypistats.org/packages/tenacity) there are approximately 15% of installations still happening from Python 2:

![image](https://user-images.githubusercontent.com/9129071/114714839-eda42e00-9d4b-11eb-81de-5358fd2e544f.png)

**Comment by and-semakin** [comment]
Also, [Python 3.5](https://github.com/jd/tenacity/blob/6855c55d9d33da3c62f12f6b198232e050b3988e/setup.cfg#L17) is deprecated as well.

**Comment by jd** [comment]
Fine with me if you go with `python_requires` so older version are available for Python 2.
I'm fine dropping Python 3.5 too.

**Comment by and-semakin** [comment]
Did some experiments and found that it's safe to drop Python 2 support right away, without needing an additional release with `python_requires` that will include `2.7`. Check it out: #293
