### ISSUE TITLE
retry on exception if only certain condition

### ISSUE THREAD

**Issue by minnieshi** [jd/tenacity#328]
more a question i think

```retry_if_result``` example is not clear to me, I'd like to know how i can pass a value to the function that will be passed to ```retry_if_result``` which basically  returns true or false.

what I'd like to achieve is:
if a function could raise an exception, and that exception can return error code, i only want to retry if:
-  it is that exception
-  and only certain error code from the exception.

`
//# def try_error_code(code):
//#     retry_list=[1, 2, 4, 17, 341, 368]
//#     print(f"log: error code {code}")
//#     if code in retry_list:
//#         return True
//#     else:
//#         return False

//# (retry_if_result(try_error_code) &
@retry(
    retry=retry_if_exception_type(FacebookRequestError),
    wait=wait_exponential(multiplier=1, max=1200),
    stop=stop_after_attempt(10),
    reraise=True,
)
def my_function_which_could_have_exception(my_parameter):
`

**Comment by asqui** [comment]
I think `retry=retry_if_exception(predicate)` is what you need for your scenario:
https://github.com/jd/tenacity/blob/a7f548520e4ee871ad8aeb354ecfa1a324c8ca19/tenacity/retry.py#L59-L69

Where `predicate` receives any exception, and checks if it's a `FacebookRequestError` and has one of the error codes you'd like to retry on.

Or, you can combine with the `retry_if_exception_type(FacebookRequestError)` that you already have, like this:
```retry=(retry_if_exception_type(FacebookRequestError) & retry_if_exception(predicate))```

In this case `predicate` will only be called if the exception is a `FacebookRequestError` so can be slightly simpler.

So a simplified version that does what you have in your example (without the logging) would be something like this:
```retry=(retry_if_exception_type(FacebookRequestError) & retry_if_exception(lambda ex: ex.code in [1, 2, 4, 17, 341, 368]))```
(Assuming that the error code of interest is available from the `FacebookRequestError.code` attribute.

**Comment by minnieshi** [comment]
I will give it a try

**Comment by minnieshi** [comment]
worked. will close the question now.
