### ISSUE TITLE
NameError: name 'wait_fixed' is not defined

### ISSUE THREAD

**Issue by nibori** [jd/tenacity#350]
![image](https://user-images.githubusercontent.com/18393365/164485977-2873007c-ed62-4591-b491-6c8cf37668c9.png)

    
  I got an error about wait_fixed when I execute this code. Seems like wait_fixed is not referenced anywhere...

**Comment by jd** [comment]
You need to import `wait_fixed`.

**Comment by nibori** [comment]
Good to know. Thanks!
