### ISSUE TITLE
Allow to raise custom Exception on failure

### ISSUE THREAD

**Issue by omeranson** [jd/tenacity#39]
Request to support raising a custom Exception on failure.

e.g.

~~~ python
@retry(stop=stop_after_attempt(7), raise=Exception("Retry failed"))
def stop_after_7_attempts():
    print("Stopping after 7 attempts")
    raise Exception("Error")

stop_after_7_attempts()
~~~

With output:
Stopping after 7 attempts
Stopping after 7 attempts
Stopping after 7 attempts
Stopping after 7 attempts
Stopping after 7 attempts
Stopping after 7 attempts
Stopping after 7 attempts
Exception: Retry failed

**Comment by jd** [comment]
What would be the point exactly?

**Comment by omeranson** [comment]
In case there is need for a custom exception to be raised when the function failed (including retries). This will save the need to surround with try/except RetryError.

**Comment by jd** [comment]
What would be the point of a custom exception? Do you have an (interesting) code example?

**Comment by omeranson** [comment]
This case: http://git.openstack.org/cgit/openstack/neutron/tree/neutron/agent/linux/ip_lib.py#n659 . The method is expected to raise AddressNotReady upon failure.

**Comment by jd** [comment]
If I understand correctly, this is already possible with `reraise`. What you want is:

```python
    def wait_until_address_ready(self, address, wait_time=30):
        """Wait until an address is no longer marked 'tentative'

        raises AddressNotReady if times out or address not present on interface
        """
        @tenacity.retry(stop=tenacity.stop.stop_after_delay(wait_time), wait=tenacity.wait.wait_fixed(0.2), reraise=True)
        def is_address_ready():
            try:
                addr_info = self.list(to=address)[0]
            except IndexError:
                raise AddressNotReady(
                    address=address,
                    reason=_('Address not present on interface'))
            if not addr_info['tentative']:
                return True
            if addr_info['dadfailed']:
                raise AddressNotReady(
                    address=address, reason=_('Duplicate address detected'))
        return is_address_read()
```

The function will re-raise the latest `AdressNotReady` error after retrying a while.

**Comment by omeranson** [comment]
All right. I'll use that.
