### ISSUE TITLE
Optionally calling sleep/after on no retry

### ISSUE THREAD

**Issue by bodenr** [jd/tenacity#41]
Today tenacity only invokes```sleep``` or ```after``` if a called function will retry [1].

What are your thoughts on making these configurable to run even if there's no retry?

Potential use cases might be introducing delay on certain conditions and/or invoking after hooks. For example [2].

Or even something as simple as:
```py
# introduce a random sleep when a timeout occurs and log it
@retry(retry= retry_if_exception_type(TimeoutErr),  wait= wait_random(), retry=retry_none(), after=log_timeout)
def might_raise_timeout(...):
```

While this usage may teeter the definition of retrying, it does provide some additional use cases.

[1] https://github.com/jd/tenacity/blob/master/tenacity/__init__.py#L187
[2] https://github.com/openstack/neutron/blob/master/neutron/common/rpc.py#L128

**Comment by jd** [comment]
I don't see why this should be the job of tenacity actually. That sounds like a normal workflow of your program, no?

**Comment by bodenr** [comment]
@jd I'm on the fence about this one.. As I mentioned IMO teeters the definition of retrying. I think it could be useful functionality, but perhaps falls outside the scope of tenacity's goals.

We can close this up if you think that's the case; just wanted to run it by you.
