### ISSUE TITLE
Allow retry_if_exception_message to specify regex flags

### ISSUE THREAD

**Issue by ryancausey** [jd/tenacity#436]
Currently, the implementation of `retry_if_exception_message` accepts a regular expression pattern in the `match` argument. This gets passed to `re.compile` and used to perform a match against the exception message.

However, since the argument is a regular expression pattern and not a `re.Pattern` object, users are unable to specify any of the regular expression flags. For example, one cannot pass `re.IGNORECASE` to specify case-insensitive matching.

A proposed solution is to allow someone to pass an already compiled regular expression, a `re.Pattern` object, into the `match` argument so the caller has full control of the regular expression used, including flags.

Relates to:

* #125 
* #127

**Comment by jd** [comment]
Not great but calling `re.compile` on a `re.Pattern` works.

**Comment by ryancausey** [comment]
Oh, I didn't realize that would work. I'll close this then.

**Comment by asqui** [comment]
I guess we should update the parameter type to capture this non-obvious flexibility?

```diff
- match: typing.Optional[str] = None,
+ match: typing.Optional[str | re.Pattern] = None,
```

in https://github.com/jd/tenacity/blob/17aefd96cbc90fd5201f61562640709a185e8796/tenacity/retry.py#L198-L205
