### ISSUE TITLE
calling retry() explicitly, not as a decorator

### ISSUE THREAD

**Issue by vadim0x60** [jd/tenacity#454]
See the code below

```
from tenacity import retry, retry_if_exception_type, stop_after_attempt, after_log

import logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

def fail():
    logger.info('about to fail')
    raise ValueError('failed')

fail_twice = retry(fail, 
    retry=retry_if_exception_type(ValueError), 
    stop=stop_after_attempt(2),
    after=after_log(logger, logging.ERROR))

fail_twice()
```

I expect it to output

```
about to fail
failed
about to fail
failed
```

but it just keeps outputting `about to fail` forever
I have tried it with tenacity 8.2.3, 7.0.0 and 6.3.1, on my main anaconda3-2023.09-0 installation and on a clean python 3.12.1 installation with no other packages

**Comment by vadim0x60** [comment]
This works fine if I replace 

```
fail_twice = retry(fail, ...)
```

with a decorator

```
@retry
def fail
```

but aren't this 2 approaches supposed to be equivalent in Python?

**Comment by asqui** [comment]
> but aren't this 2 approaches supposed to be equivalent in Python?

Not quite.

The equivalent to:
```
@retry(...)
def fail():
```

Is:
```
fail_twice = retry(...)(fail)
```

**Comment by vadim0x60** [comment]
Ah! got it
