### ISSUE TITLE
Any help needed for a new release?

### ISSUE THREAD

**Issue by ichard26** [jd/tenacity#458]
The latest release, tenacity 8.2.3, is ~9 months old. It would be great to see a new release soon. I'd love to incorporate #450 into the next release of pip sometime. If you need any help @jd, let me know!

**Comment by jd** [comment]
I was waiting for https://github.com/jd/tenacity/pull/451 to go in first, but I'll do a release today.

**Comment by jd** [comment]
8.3.0 is out.
