### ISSUE TITLE
implement @retry_once and @retry_twice

### ISSUE THREAD

**Issue by ssbarnea** [jd/tenacity#47]
Because the default behaviour is to retry forever I would like to suggest implementing  `@retry_once` and `@retry_twice` as much easier to use alternatives.

**Comment by jd** [comment]
I'm not sure it's way more interesting than `@retry(stop_after_attempt(1))`. Or do I miss something?

**Comment by ssbarnea** [comment]
When I proposed this, I had in mind **simplicity**, no params. Why needing to remember some not-obvious parameters when we can have a simple "alias" that does not need explanations?

If we would have something like `@retry(count=2)` probably this would not be needed, but current syntax is not very friendly and considerably more verbose. I think I know why we have this but this should not providing a simple and clean syntax for the most used use-cases.

Note: I am currently using `flaky` for retrying unit tests and the default behaviour is to try twice instead of infinitely, something that I like. I am aware that changing defaults would be out of the question as nobody likes broken APIs.

**Comment by jd** [comment]
The problem is that there are so many use cases that I find it hard to create "aliases" for all of them. `retry_once`, `retry_twice`, `retry_three_times_only_if_the_exception_is_IOError`, etc? That's why the approach of tenacity is very functional.

Though if you always want to retry twice in your code, then you can easily define your own function:

```python
retry_twice = retry(stop=stop_after_attempt(2))
```
And be done with it.

**Comment by ssbarnea** [comment]
Thanks. That what I am probably going to do. I do understand that it would be nonesense to create aliases for all kind of combinations. Still my proposal was only for a basic one. If anyone else would be looking for the same they are welcomed to use +/- voting buttons.

BTW, I think that a feature to change the default values (persistent values) could also make this request obsolete. If you could change the defaults after import to make the retry run only twice when no params are specified, people could configure them once and still be using the short form `@retry` in their code.
