### ISSUE TITLE
weird installation error with 2.7.1: tenacity-3.7.1/setup.cfg: TypeError: dist must be a Distribution instance',)

### ISSUE THREAD

**Issue by ssbarnea** [jd/tenacity#49]
I got this weird error [here](https://circleci.com/gh/pycontribs/jira/5?utm_campaign=build-failed&utm_medium=email&utm_source=notification):
```
File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/pbr/core.py", line 119, in pbr
    'Error parsing %s: %s: %s' % (path, e.__class__.__name__, e))
setuptools.sandbox.UnpickleableException: DistutilsSetupError('Error parsing /tmp/easy_install-81hJTS/tenacity-3.7.1/setup.cfg: TypeError: dist must be a Distribution instance',)
```

tenacity is only listed as a dependency so I am not sure what causes it but I suspect that its setup.cfg may be more than distutils can handle.

**Comment by jd** [comment]
I am not able to reproduce it and understand where it comes from exactly. It might be a little bug in pbr. I wonder if it's not related to Python 2, do you have the same error with Python 3?
