### ISSUE TITLE
End without exception

### ISSUE THREAD

**Issue by xoac** [jd/tenacity#50]
```
 @tenacity.retry(retry=tenacity.retry_if_result(Common.IsNonePtr), stop=tenacity.stop_after_attempt(7), reraise=False)
    def get_net_addr(self, uid):
             return None
```
Is it possible to end this without RetryError? After 7 attpemts it's fine to return None.

**Comment by jd** [comment]
No, it's up to the caller to decide that.

```python
try:
    ret = get_net_addr(uid)
except tenacity.RetryError:
    ret = None
```

I think it's safer to do that, designing a function that returns None after a few retries feels like a clumsy design.
