### ISSUE TITLE
any plan to support python 2.7?

### ISSUE THREAD

**Issue by alburthoffman** [jd/tenacity#52]
Hi,

ur module tenacity is quite useful actually. but noticed it depends on concurrent module in python 3.
so I wonder if any plan to support python 2.7? that would help for old systems.

Regards

**Comment by jd** [comment]
As you can see here https://github.com/jd/tenacity/blob/master/setup.cfg#L14 it supports Python 2.7.

**Comment by RonnyPfannschmidt** [comment]
@jd i believe a extra dependency is needed for concurrent.futures for the python 2 backport

**Comment by RonnyPfannschmidt** [comment]
ah, forget what i wrote, i got tricked by the prb thing again
