### ISSUE TITLE
`before` callback on first success

### ISSUE THREAD

**Issue by JasonTam** [jd/tenacity#53]
```
@retry(before=lambda *args: print('This should only occur on retries(?)'))
def unstable():
    return
```
This prints out `This should only occur on retries(?)`

Is this intended? I thought the callback should only be invoked on retries of the method `unstable` -- not if it succeeds on the first try.

I've been using `after` instead. But I was just unsure of the intentions here...

**Comment by RonnyPfannschmidt** [comment]
my understanding is that before happens before every single call, after all its used for logging (see the before log)

however it will get the function to call and the try number as arguments

**Comment by RonnyPfannschmidt** [comment]
bascially see https://github.com/jd/tenacity/blob/master/tenacity/before.py

**Comment by jd** [comment]
Right, I think the behavior is correct but the README is unclear. I'll fix it.
