### ISSUE TITLE
How is this package different from retrying?

### ISSUE THREAD

**Issue by mmautner** [jd/tenacity#73]
What was the purpose of forking the [retrying repo](https://github.com/rholder/retrying)? This project's README is identical besides mentioning:

> It originates from a fork of Retrying

It might be helpful to add more documentation + a changelog that makes it easier for new users to decide whether to use this package vs. `retrying`.

**Comment by mmautner** [comment]
Maybe provide links to here?

- https://julien.danjou.info/blog/2017/python-tenacity
- https://github.com/rholder/retrying/issues/65

**Comment by jd** [comment]
Fixed in https://github.com/jd/tenacity/commit/8253e90a73576a7895afa7f97c617c9aea6cca34
