### ISSUE TITLE
Multiple "stop" conditions

### ISSUE THREAD

**Issue by cher-nov** [jd/tenacity#74]
Is this possible? For example, 7 attempts with 10 seconds timeout each.
The documentation is unclear of it. :c

**Comment by jd** [comment]
Do you mean `stop=stop_after_attempt(7), wait=wait_fixed(10)` ?

**Comment by cher-nov** [comment]
No, I meant something like
```python
@retry(stop=(stop_after_attempt(5) | stop_after_delay(10)))
```
It's also unclear how to set timeout for all attempts in total or each of them.

**Comment by bobbywatson3** [comment]
Was there ever an answer to this? I'd also like to be able to stop if either max attempts or max time limit is reached.
