### ISSUE TITLE
Usage with threaded functions?

### ISSUE THREAD

**Issue by cher-nov** [jd/tenacity#75]
Is it possible? Threading isn't mentioned ever in manual.

**Comment by jd** [comment]
Really depends on what you do. You can use threads, but the `Retrying` objects are not thread-safe themselves I think.

**Comment by cher-nov** [comment]
I would run by 10 `Thread()`'s a function decorated as
```python
@retry(stop=stop_after_attempt(10), wait=wait_fixed(10))
```

**Comment by jd** [comment]
I don't think that safe right now. The underlying `Retrying` object is not thread-safe.

**Comment by cher-nov** [comment]
Found a workaround: it's possible to wrap it into another function, so objects used by decorator will be different in different threads.
```python
def thread_func():
    @retry(stop=stop_after_attempt(10), wait=wait_fixed(10))
    def worker_func():
        # some code here
    return

for _ in range(5):
    t = Thread(target=thread_func)
```
