### ISSUE TITLE
Reset stop conditions

### ISSUE THREAD

**Issue by cher-nov** [jd/tenacity#76]
Assume we have next function:

```python
@retry(stop=stop_after_attempt(3))
def test_function():
    # while loop that does jobs
    # every successful iteration is a completed job
    while not stop_event.is_set():
        # some code that can raise exception
```

Here we have counter that decreases on every failed job. But due to the while loop, it becomes a counter of failed jobs instead of attempt counter.
Although I could separate the job completion code into another function, there's another problem: every next job needs data from some previous jobs. So I will need to use outer data, what is slightly non-pythonic, I believe.

Proposal is to add functions to reset stop conditions (all and/or specific).

**Comment by jd** [comment]
I am sorry but it's not really clear. Can you provide a full small example of what you can't and want to achieve?

Keep in mind this is a retrying library. Not a general iteration library.

**Comment by georgepsarakis** [comment]
@cher-nov as you said I think you need to separate the logic into two different functions, the main/current one that contains the while loop and another one that will use `retrying`:

```
def main_function():
     previous_job = None
     while not stop_event.is_set():
         current_job = process_job(..., previous=previous_job)
         # ...
         previous_job = current_job

@retry(stop=stop_after_attempt(3))
def process_job(..., previous=None):
    ...
```

**Comment by cher-nov** [comment]
@georgepsarakis Thank you, I know about this workaround, but the problem is I need data from ALL jobs done.

**Comment by cher-nov** [comment]
@jd
```python
@retry(stop=stop_after_attempt(3))
def test_function():
    # while loop that does jobs
    # every successful iteration is a completed job
    while not stop_event.is_set():
        # some code that can raise exception #
        test_function.retry.attempt_number = 1  # <-- something like that,
                                                # but at the library-level
```

**Comment by jd** [comment]
@cher-nov you're providing a solution in https://github.com/jd/tenacity/issues/76#issuecomment-309284790 but I would actually like to know what's the problem in the solution proposed by @georgepsarakis in https://github.com/jd/tenacity/issues/76#issuecomment-309284104

IIUC all you want to do is to retry each job up to 3 times and give up if it fails. That's what @georgepsarakis wrote. You can store all the job result in a list if you need them all in the end.

**Comment by cher-nov** [comment]
> You can store all the job result in a list if you need them all in the end.

this. But to access that list I must either write `process_job` function as nested or pass it a reference to the list. Both solutions not so beautiful IMHO. :)

**Comment by jd** [comment]
Writing functional code and separating the retry condition from the general workflow still sounds better to me.

Also you can do something like

```
attempt = stop_after_attempt(3)

@retry(stop=attempt)
def test_function():
    # while loop that does jobs
    # every successful iteration is a completed job
    while not stop_event.is_set():
        # some code that can raise exception
        attempt.max_attempt_number += 1
```

Or write your own stop function/class in the end. :)
