### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by jonparrott** [jd/tenacity#81]
tenacity can build as a universal wheel, but it seems like these wheels aren't being upload to PyPI. Pretty please upload wheels? :)

**Comment by jd** [comment]
I plan to automate upload using Travis as I've seen it possible. I'll do wheels at the same time.

**Comment by jonparrott** [comment]
Thanks!

**Comment by RonnyPfannschmidt** [comment]
given that you use pbr, its just a tag based deploy added to the travis config away
