### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by adamrothman** [jd/tenacity#83]
Please excuse me if this exists and I just couldn't find it – but is there a changelog available somewhere? The releases at https://github.com/jd/tenacity/releases are not annotated and I couldn't find anything like a changelog in the documentation (http://tenacity.readthedocs.io/).

A number of tools exist that can automatically generate changelog entries from commit history – at a minimum it would be helpful to have something like this so that consumers of tenacity can understand what we're getting when we upgrade from one version to another.

**Comment by jd** [comment]
No, for now the best changelog is `git log`, which might not be user friendly.
If anyone wants to help setup http://pypi.python.org/pypi/reno in place I'd be ok to use it.
