### ISSUE TITLE
Take over any of the 'intersting' functionality of oslo.service.loopingcall

### ISSUE THREAD

**Issue by harlowja** [jd/tenacity#9]
It'd be nice to extract anything useful from:

https://github.com/openstack/oslo.service/blob/master/oslo_service/loopingcall.py

So that we (oslo/openstack) can eventually remove that code (since it is really the same stuff at its core as this library).

**Comment by jd** [comment]
Ok, as long as you make it generic – I read too much of eventlet in there.

If there's some process related, @sileht already wrote a better alternative to oslo.service at https://github.com/sileht/cotyledon FWIW.

**Comment by harlowja** [comment]
Cool didn't know about `cotyledon `

**Comment by sileht** [comment]
Ceilometer/Aodh uses:
* cotelydon to replace https://github.com/openstack/oslo.service/blob/master/oslo_service/service.py
and 
* futurist to replace https://github.com/openstack/oslo.service/blob/master/oslo_service/loopingcall.py

**Comment by harlowja** [comment]
Ya, fair enough, loopingcall (perhaps all of oslo.service?) stuff really is I guess not needed anymore after this lib, cotelydon and futurist.

The only thing different is the ability to periodically call things, but futurist does that in a different (more integrated with non-eventlet-things way I suppose anyway); so maybe there isn't anything left to extract, lol.

**Comment by jd** [comment]
Closing until we have a precise list of things we want to backport.
