### ISSUE TITLE
"KeyError: sleep" in repr(BaseRetrying) and repr(AsyncRetrying)

### ISSUE THREAD

**Issue by mikek** [jd/tenacity#92]
There would a `KeyError: sleep` if anyone tries to call `repr(BaseRetrying)` or `repr(AsyncRetrying)` because `sleep` is not part of the context for them: https://github.com/jd/tenacity/blob/73ff6ec7b9412e0c7dd8df339f3dcd482cbf9eb0/tenacity/__init__.py#L133
I've came up with an ugly fix: https://gist.github.com/mikek/68ad4d5c79ba60f6ddffeb600884881d
Is this something I should make into a PR?

**Comment by georgepsarakis** [comment]
@mikek why not initialize the `sleep` property, as public, in the [constructor](https://github.com/jd/tenacity/blob/73ff6ec7b9412e0c7dd8df339f3dcd482cbf9eb0/tenacity/__init__.py#L124) of `BaseRetrying` to a `None` value?

**Comment by mikek** [comment]
@georgepsarakis 
My first intent was not to introduce a base class attribute just to satisfy the hardcoded `repr()` string, but you're probably right – this is too complicated =)
