### ISSUE TITLE
retry_on_no_exception

### ISSUE THREAD

**Issue by mwichtlh** [jd/tenacity#94]
I am using tenacity for integration testing of networking code.

Quite frequently I have to retry on a condition n times within m seconds, where the condition may not fail a single time within that time frame.

Thus, it would helpful to have a "retry_on_no_exception" option similar to the "retry_on_exception" option.

The expected behavior of the "retry_on_no_exception" option is to ...
- ... retry if no exception occurs.
- ... stop retrying and raising whichever exception has occurred, if an exception occurred.

PS: I also posted this issue for the retrying package. I have closed the issue there as the retrying repos seems to be unmaintained.

**Comment by jd** [comment]
IIUC what you want is already possible with:

```python
tenacity.Retrying(retry=retry_unless_exception_type(), reraise=True)
```
