### ISSUE TITLE
Catch specific exception

### ISSUE THREAD

**Issue by wontonst** [jd/tenacity#98]
It seems odd to me that tenacity tries to catch Exception. What if an exception that I don't want caught is thrown? e.g. some code used to grab an API hits a MemoryError from OOM. I want the OOM to propagate up rather than get caught by tenacity and then start another retry.

TLDR something like

`@retry(exception_type=MyCustomException)`

**Comment by jd** [comment]
`@retry(retry=retry_if_exception_type(MyCustomException))`

Just check the README file.
